# Generated by Django 5.1.2 on 2025-03-14 15:26

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(default='https://st2.depositphotos.com/1105977/9877/i/450/depositphotos_98775856-stock-photo-retro-film-production-accessories-still.jpg', max_length=255)),
                ('vertical_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, max_length=150, null=True)),
                ('sponsor_video', models.URLField(blank=True, null=True)),
                ('actors', models.JSONField(blank=True, default=tickets.models.default_empty_list)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=tickets.models.default_empty_list)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('hall', models.CharField(max_length=50)),
                ('total_seats', models.IntegerField(default=100)),
                ('available_seats', models.IntegerField(default=100)),
                ('ticket_price', models.FloatField()),
                ('reserved_seats', models.JSONField(blank=True, default=tickets.models.default_empty_list)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='tickets.movie')),
            ],
            options={
                'unique_together': {('movie', 'date', 'time', 'hall')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservations_code', models.CharField(blank=True, editable=False, max_length=6, unique=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reservations', to='tickets.guest')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_reservations', to='tickets.movie')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tickets.showtime')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='show_times',
            field=models.ManyToManyField(blank=True, related_name='movies', to='tickets.showtime'),
        ),
    ]
