# Generated by Django 5.1.2 on 2025-03-13 10:33

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('show_times', models.JSONField(default=dict)),
                ('seats', models.IntegerField(default=100)),
                ('available_seats', models.IntegerField(default=100)),
                ('reservations', models.IntegerField(blank=True, default=0)),
                ('photo', models.CharField(default='https://st2.depositphotos.com/1105977/9877/i/450/depositphotos_98775856-stock-photo-retro-film-production-accessories-still.jpg', max_length=255)),
                ('vertical_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_price', models.FloatField()),
                ('reserved_seats', models.JSONField(blank=True, default=tickets.models.default_empty_list)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, max_length=150, null=True)),
                ('sponsor_video', models.URLField(blank=True, null=True)),
                ('actors', models.JSONField(blank=True, default=tickets.models.default_empty_list)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=tickets.models.default_empty_list)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservations_code', models.CharField(blank=True, editable=False, max_length=6, unique=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reservations', to='tickets.guest')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_reservations', to='tickets.movie')),
            ],
        ),
    ]
