# Generated by Django 5.1.2 on 2025-03-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='age',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='seat_price',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='show_time',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='total_price',
        ),
    ]
