# Generated by Django 5.1.2 on 2025-03-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_movie_show_times_alter_showtime_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
    ]
