# Generated by Django 5.1.2 on 2025-03-13 12:25

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_guest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reserved_seats',
            field=models.JSONField(blank=True, default=tickets.models.default_empty_list),
        ),
    ]
