# Generated by Django 5.1.2 on 2025-03-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_seats',
            field=models.JSONField(default=list),
        ),
    ]
