# Generated by Django 5.1.2 on 2024-10-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_movie_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='short_description',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
